Add files via upload
mcdougallab/pipeline pull request #27
Opened 2021-03-30 16:26 UTC by gmichel

Added getuserdataquery, returns all documents where the local_data elements are not all empty.

2021-04-01 02:58 UTC, gmichel commented
I deleted the files in the Project folder and moved them from pipeline to Project.
George

From: ramcdougal ***@***.***>
Sent: Wednesday, March 31, 2021 5:20 PM
To: mcdougallab/pipeline ***@***.***>
Cc: Michel, George ***@***.***>; Author ***@***.***>
Subject: Re: [mcdougallab/pipeline] Add files via upload (#27)


@ramcdougal requested changes on this pull request.

These files belong in the Project folder. Until that happens, I can't see what's changed.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmcdougallab%2Fpipeline%2Fpull%2F27%23pullrequestreview-625728537&data=04%7C01%7Cgeorge.michel%40yale.edu%7Cbb7f7f344f90435aad5c08d8f48ad015%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637528224342676289%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hyg%2BjowYRgQ%2BScSkvjO%2FNsEwwd16nLLrtEq3H4KR%2BUI%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAADSOO3HRHZCRJ7WSBAQW73TGOGZ3ANCNFSM42CNYYYA&data=04%7C01%7Cgeorge.michel%40yale.edu%7Cbb7f7f344f90435aad5c08d8f48ad015%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637528224342686289%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xS4TJ85vE8HpA5ySk%2Bi0CrXioUuAglmsOU9wjUKGjbQ%3D&reserved=0>.

2021-04-01 03:16 UTC, ramcdougal requested changes

2021-04-01 03:16 UTC, ramcdougal commented on Project/pipeline_models.py
>  def update_userdata(paper_id, userdata):
I assume you didn't mean to delete this?

2021-04-01 03:16 UTC, ramcdougal commented on Project/pipeline_views.py
> +    context = {"title": base_context["toolname"], "index_content": index_content}
I assume you didn't mean to change this?

2021-04-01 03:16 UTC, ramcdougal commented on Project/pipeline_views.py
> +    try:
I assume you didn't mean to change this?

2021-04-01 03:16 UTC, ramcdougal commented on Project/pipeline_views.py
> +@csrf_protect
This and line 319 below would mean the user has to be logged in. Was that on purpose?

I'm not inherently opposed but I don't know how to have a script do that with this particular website.

2021-04-01 03:16 UTC, ramcdougal commented on Project/pipeline_views.py
> +        response = HttpResponse(models.getdocsforuserdata())
Better to use a JsonResponse here. See https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.JsonResponse

Two reasons: (1) as-is, it returns Python's serialization of dictionaries rather than JSON per se, and there are subtle differences  (e.g. True vs true). When you do this, you'll probably find you need to replace the _id objects with their string representation. (2) JsonResponse sets the Content-type header correctly. This should otherwise be set explicitly.

2021-04-06 22:13 UTC, ramcdougal commented
Superseded by a50c9b3

2021-04-06 22:13 UTC, closed without merging